services:
  - type: web
    name: ecommerce-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn wsgi:application
    postStartCommand: python backend/seed_enhanced_db.py
    plan: free
  - type: web
    name: ecommerce-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: REACT_APP_API_URL
        value: https://ecommerce-backend.onrender.com
    plan: free

databases:
  - name: ecommerce-db
    databaseName: ecommerce
    user: ecommerce_user
    plan: free 