services:
  - type: web
    name: ecommerce-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn wsgi:application
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: REDIS_URL
        fromService:
          type: redis
          name: ecommerce-redis
          property: connectionString
    github:
      repo: charan22640/Ecommerce-Sales-Chatbot
      branch: master
    plan: free

  - type: web
    name: ecommerce-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: REACT_APP_API_URL
        value: https://ecommerce-backend.onrender.com
    github:
      repo: charan22640/Ecommerce-Sales-Chatbot
      branch: master
    plan: free

databases:
  - name: ecommerce-db
    databaseName: ecommerce
    user: ecommerce_user
    plan: free

redis:
  - name: ecommerce-redis
    plan: free 