services:
  - type: web
    name: ecommerce-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn wsgi:application
    plan: free
  - type: web
    name: ecommerce-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    plan: free

databases:
  - name: ecommerce-db
    databaseName: ecommerce
    user: ecommerce_user
    plan: free

redis:
  - name: ecommerce-redis
    plan: free 