services:
  - type: web
    name: ecommerce-backend
    env: python    buildCommand: |
      cd backend && pip install -r requirements.txt && pip install redis
      python seed_enhanced_db.py
    startCommand: cd backend && gunicorn wsgi:application --bind 0.0.0.0:$PORT --config gunicorn.conf.py
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: SECRET_KEY
        generateValue: true
      - key: REDIS_URL
        fromService:
          type: redis
          name: ecommerce-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: ecommerce-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: ecommerce-redis
          property: connectionString  - type: web
    name: ecommerce-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview    envVars:
      - key: PORT
        value: 4173
      - key: VITE_API_URL
        value: https://ecommerce-backend-oyo1.onrender.com/api
    plan: free

databases:
  - name: ecommerce-db
    databaseName: ecommerce
    user: ecommerce_user
    plan: free

redis:
  - name: ecommerce-redis
    plan: free 